"""add field code in Program

Revision ID: 4ffe738ee0b7
Revises: adf13cc7997e
Create Date: 2025-02-23 16:41:01.446573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffe738ee0b7'
down_revision: Union[str, None] = 'adf13cc7997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('code', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'code')
    # ### end Alembic commands ###
